guest = ['John','Mark','Jennie','Anne']
print(guest[0] +", You are invited to the dinner this Saturday!")
print(guest[1] +", You are invited to the dinner this Saturday!")
print(guest[2] +", You are invited to the dinner this Saturday!")
print(guest[3] +", You are invited to the dinner this Saturday!")
print("\n")
print(guest[0]+ " can't make it this Saturday")
print("\n")
guest.remove('John')
guest.append('Lisa')
print(guest[0] +", You are invited to the dinner this Saturday!")
print(guest[1] +", You are invited to the dinner this Saturday!")
print(guest[2] +", You are invited to the dinner this Saturday!")
print(guest[3] +", You are invited to the dinner this Saturday!")
print("\n")
print("We've got a bigger table!")
guest.insert(0,'Rose')
guest.insert(-1,'Annie')
guest.append('Josh')
print(guest[0] +", You are invited to the dinner this Saturday!")
print(guest[1] +", You are invited to the dinner this Saturday!")
print(guest[2] +", You are invited to the dinner this Saturday!")
print(guest[3] +", You are invited to the dinner this Saturday!")
print(guest[4] +", You are invited to the dinner this Saturday!")
print(guest[5] +", You are invited to the dinner this Saturday!")
print(guest[6] +", You are invited to the dinner this Saturday!")

