guest = ['John','Mark','Jennie','Anne']
print(guest[0] +", You are invited to the dinner this Saturday!")
print(guest[1] +", You are invited to the dinner this Saturday!")
print(guest[2] +", You are invited to the dinner this Saturday!")
print(guest[3] +", You are invited to the dinner this Saturday!")
print("\n")
print(guest[0]+ " can't make it this Saturday")
print("\n")
guest.remove('John')
guest.append('Lisa')
print(guest[0] +", You are invited to the dinner this Saturday!")
print(guest[1] +", You are invited to the dinner this Saturday!")
print(guest[2] +", You are invited to the dinner this Saturday!")
print(guest[3] +", You are invited to the dinner this Saturday!")
print("\n")
print("We've got a bigger table!")
guest.insert(0,'Rose')
guest.insert(-1,'Annie')
guest.append('Josh')
print(guest[0] +", You are invited to the dinner this Saturday!")
print(guest[1] +", You are invited to the dinner this Saturday!")
print(guest[2] +", You are invited to the dinner this Saturday!")
print(guest[3] +", You are invited to the dinner this Saturday!")
print(guest[4] +", You are invited to the dinner this Saturday!")
print(guest[5] +", You are invited to the dinner this Saturday!")
print(guest[6] +", You are invited to the dinner this Saturday!")
print("\n")
print("Sorry i can only invite two people to dinner.")
x = guest.pop(0)
print("Sorry " + x.title()+ " there's not enough room at the table.")
x1 = guest.pop(1)
print("Sorry " + x1.title() + " there's not enough room at the table.")
x2 = guest.pop(2)
print("Sorry " + x2.title() + " there's not enough room at the table.")
x3 = guest.pop(3)
print("Sorry " + x3.title() + " there's not enough room at the table.")
xx = guest.pop(-1)
print("Sorry " + xx.title() + " there's not enough room at the table.")
print("Dear " + guest[0].title() + ", please come to the dinner.")
print("Dear " + guest[1].title() + ", please come to the dinner.")
del (guest[0])
del (guest[0])
print(guest)
